[32m2023-10-09 15:57:17 +1100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - aee56771-3a01-4068-923e-108896521eaf - 29246 - LOGS_CAPTURED - Started capturing logs in process (pid: 29246).
[32m2023-10-09 15:57:17 +1100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - aee56771-3a01-4068-923e-108896521eaf - 29246 - call_property_list_api - STEP_START - Started execution of step "call_property_list_api".
[32m2023-10-09 15:57:20 +1100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - aee56771-3a01-4068-923e-108896521eaf - 29246 - call_property_list_api - STEP_OUTPUT - Yielded output "result" of type "DataFrame". (Type check passed).
[32m2023-10-09 15:57:20 +1100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - aee56771-3a01-4068-923e-108896521eaf - 29246 - call_property_list_api - STEP_FAILURE - Execution of step "call_property_list_api" failed.

dagster._core.errors.DagsterInvalidDefinitionError: Asset ['duckdb', 'raw_data', 'call_property_list_api'] specifies a schema with its key prefixes ['duckdb', 'raw_data'], but schema  raw was also provided via run config. Schema can only be specified one way.

Stack Trace:
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 273, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 482, in core_dagster_event_sequence_for_step
    for evt in _type_check_and_store_output(step_context, user_event):
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 533, in _type_check_and_store_output
    for evt in _store_output(step_context, step_output_handle, output):
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 724, in _store_output
    for elt in iterate_with_context(
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 443, in iterate_with_context
    next_output = next(iterator)
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 714, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/storage/db_io_manager.py", line 123, in handle_output
    table_slice = self._get_table_slice(context, context)
  File "/Users/cooperwhite/miniconda3/envs/dagster/lib/python3.10/site-packages/dagster/_core/storage/db_io_manager.py", line 176, in _get_table_slice
    raise DagsterInvalidDefinitionError(
[0m
